### PR TITLE
Fix encode optarg option

### PR DESCRIPTION
**Pull request by jiceher**
* Fix typo encode should 'e' optarg option
* enable to set 'atrac3' argument to optarg

Signed-off-by: JiCeheR <jiceher@free.fr>

### CODE REVIEW

**Comment by dcherednik** [comment]
Thank you! Merged.

**Comment by joshuadavila** [comment]
Hi, great job! I would like to help to improve this project.  I have tested the atrac3 encoder on some audio files and successfully played them on the real hardware. 
Do you have information about the algorithm you are using?

**Comment by dcherednik** [comment]
Hi. There are no open specifications for ATRAC. All informations I got by reading ffmpeg decoder source code, articles https://wiki.multimedia.cx/index.php/RealAudio_atrc and minidisc.org. For psychoacoustics I used simple idea described here: http://www.minidisc.org/aes_atrac.html. Actually ATRAC and ATRAC3 (not ATRAC3PLUS) are quite simple.

About improvement: for ATRAC3 gain control should be implemented. This is feature used to reduce preecho artifact. This is important (even critical) part because ATRAC3 has no long/short window switch. And it is interested part but required good understanding MDCT and some time for experiments with real signals. But it should make significant improvement of quality.
Also right now I encode left and right channels completely independent (each channel got 66Kbit/s in case of LP2), but for ATRAC3 we can allocate bitrate according to channel signal. Moreover LP4 mode required JointStereo. So we need to make some refactoring to implement it. It should not be difficult.
And of course, good idea is to add proper psychoacoustic model.

**Comment by jiceher** [comment]
It seems that some of you succeed to play ATRAC3 encoded on your device. How did you download it? Under which operating system ?

**Comment by joshuadavila** [comment]
i have successfully encoded a 16 bit/44100Hz wav file using this encoder, then i copied the encoded audio content to a wav container using ffmpeg, and then used the linux-minidisc netmdcli utility to send it to a NetMD. I did it using macos, but it also works on linux and windows. 

I know it looks like a lot of trouble just to hear a song on a minidisc player, but i was thinking about integrate all the encoder/sender functions on a single app.

**Pull request merged**
